# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class ui_auv(object):
    def setupUi(self, auv):
        auv.setObjectName('auv')
        auv.resize(1305, 834)
        auv.setMaximumSize(1305, 834)
        auv.setMinimumSize(1305, 834)
        auv.setWindowTitle("AUV 控制台")

        # Set Icon
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("smu_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        auv.setWindowIcon(icon)

        # Set Font
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        auv.setFont(font)

        # Set Underwater Video Ui
        self.textBrowser = QtWidgets.QTextBrowser(auv)
        self.textBrowser.setGeometry(QtCore.QRect(490, 40, 671, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(auv)
        self.label.setGeometry(QtCore.QRect(800, 20, 61, 17))
        self.label.setObjectName("label")
        self.label.setText("水下图像")

        # Set Sensor Data Receive Ui
        self.label_0 = QtWidgets.QLabel(auv)
        self.label_0.setGeometry(QtCore.QRect(260, 20, 81, 17))
        self.label_0.setMinimumSize(QtCore.QSize(81, 17))
        self.label_0.setMaximumSize(QtCore.QSize(81, 17))
        self.label_0.setObjectName("label_0")
        self.label_0.setText("传感器数据")

        # Set GridLayout1 Ui
        self.widget = QtWidgets.QWidget(auv)
        self.widget.setGeometry(QtCore.QRect(160, 30, 321, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setMinimumSize(QtCore.QSize(67, 25))
        self.label_1.setMaximumSize(QtCore.QSize(67, 25))
        self.label_1.setObjectName("label_1")
        self.label_1.setText("经度")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        # Set GridLayout2 Ui
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(67, 25))
        self.label_2.setMaximumSize(QtCore.QSize(67, 25))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("纬度")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setReadOnly(True)
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        # Set GridLayout3 Ui
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(67, 25))
        self.label_3.setMaximumSize(QtCore.QSize(67, 25))
        self.label_3.setObjectName("label_3")
        self.label_3.setText("深度")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setReadOnly(True)
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        # Set GridLayout4 Ui
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(67, 25))
        self.label_4.setMaximumSize(QtCore.QSize(67, 25))
        self.label_4.setObjectName("label_4")
        self.label_4.setText("俯仰角")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setReadOnly(True)
        self.gridLayout_4.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)

        # Set GridLayout5 Ui
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(67, 25))
        self.label_5.setMaximumSize(QtCore.QSize(67, 25))
        self.label_5.setObjectName("label_5")
        self.label_5.setText("横滚角")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setReadOnly(True)
        self.gridLayout_5.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)

        # Set GridLayout6 Ui
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(67, 25))
        self.label_6.setMaximumSize(QtCore.QSize(67, 25))
        self.label_6.setObjectName("label_6")
        self.label_6.setText("艏向角")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setReadOnly(True)
        self.gridLayout_6.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)

        # Set PushButton 0
        self.pushButton0 = QtWidgets.QPushButton(auv)
        self.pushButton0.setGeometry(QtCore.QRect(260, 370, 100, 25))
        self.pushButton0.setObjectName("pushButton0")
        self.pushButton0.setText("关闭")
        self.pushButton0.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton0.setMinimumSize(QtCore.QSize(100, 25))

        # Set Mode Select Ui
        self.radioButton = QtWidgets.QRadioButton(auv)
        self.radioButton.setGeometry(QtCore.QRect(260, 440, 117, 22))
        self.radioButton.setMinimumSize(QtCore.QSize(117, 25))
        self.radioButton.setMaximumSize(QtCore.QSize(117, 25))
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setText("自动模式")

        self.radioButton1 = QtWidgets.QRadioButton(auv)
        self.radioButton1.setGeometry(QtCore.QRect(1000, 440, 117, 22))
        self.radioButton1.setMinimumSize(QtCore.QSize(117, 25))
        self.radioButton1.setMaximumSize(QtCore.QSize(117, 25))
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton1.setText("手动模式")

        # Set Auto Mode Part Ui
        self.widget1 = QtWidgets.QWidget(auv)
        self.widget1.setGeometry(QtCore.QRect(200, 500, 220, 100))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setMinimumSize(QtCore.QSize(70, 25))
        self.label_7.setMaximumSize(QtCore.QSize(70, 25))
        self.label_7.setObjectName("label_7")
        self.label_7.setText("深度设定")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_8.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.verticalLayout_1.addLayout(self.gridLayout_8)

        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setMinimumSize(QtCore.QSize(70, 25))
        self.label_8.setMaximumSize(QtCore.QSize(70, 25))
        self.label_8.setObjectName("label_8")
        self.label_8.setText("航向设定")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_9.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.verticalLayout_1.addLayout(self.gridLayout_9)

        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setMinimumSize(QtCore.QSize(70, 25))
        self.label_9.setMaximumSize(QtCore.QSize(70, 25))
        self.label_9.setObjectName("label_9")
        self.label_9.setText("速度设定")
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_10.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.verticalLayout_1.addLayout(self.gridLayout_10)

        # Set Manual Mode Part Ui
        self.widget2 = QtWidgets.QWidget(auv)
        self.widget2.setGeometry(QtCore.QRect(920, 500, 220, 100))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setMinimumSize(QtCore.QSize(70, 25))
        self.label_10.setMaximumSize(QtCore.QSize(70, 25))
        self.label_10.setObjectName("label_10")
        self.label_10.setText("垂直舵角")
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_11.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)


        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setMaximumSize(QtCore.QSize(70, 25))
        self.label_11.setMinimumSize(QtCore.QSize(70, 25))
        self.label_11.setObjectName("label_11")
        self.label_11.setText("水平舵角")
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_11.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_12.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_12)

        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setMaximumSize(QtCore.QSize(70, 25))
        self.label_12.setMinimumSize(QtCore.QSize(70, 25))
        self.label_12.setObjectName("label_11")
        self.label_12.setText("电机转速")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(113, 25))
        self.lineEdit_12.setMinimumSize(QtCore.QSize(113, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_13.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)

        # Set PushButtons 1-3
        self.pushButton1 = QtWidgets.QPushButton(auv)
        self.pushButton1.setGeometry(QtCore.QRect(260, 650, 100, 25))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1.setText("确认发送")
        self.pushButton1.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton1.setMinimumSize(QtCore.QSize(100, 25))

        self.pushButton2 = QtWidgets.QPushButton(auv)
        self.pushButton2.setGeometry(QtCore.QRect(1000, 650, 100, 25))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.setText("确认发送")
        self.pushButton2.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton2.setMinimumSize(QtCore.QSize(100, 25))

        self.pushButton3 = QtWidgets.QPushButton(auv)
        self.pushButton3.setGeometry(QtCore.QRect(640, 730, 120, 35))
        self.pushButton3.setObjectName("pushButton4")
        self.pushButton3.setText("复位")


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = ui_auv()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
